### ISSUE TITLE
CALC not recognizing numbers and math

### ISSUE THREAD

**Issue by Icohedron** [Aquafina-water-bottle/Command-Compiler-Unlimited#3]
Input:
```
DEF MAX_INT CALC(2^31 - 1)
summon AreaEffectCloud ~ ~ ~ {Duration:MAX_INT}
```
Output:
```
ERROR: The first number in '2^31 - 1' in line 'summon AreaEffectCloud ~ ~ ~ {Duration:CALC(2^31 - 1)}' must be a number
```

**Comment by Aquafina-water-bottle** [comment]
CALC, and all other math-related stuff should have spaces in between all numbers and operators (for now at least). In this case, it should read
```
DEF MAX_INT CALC(2 ^ 31 - 1)
summon AreaEffectCloud ~ ~ ~ {Duration:MAX_INT}
```

(oh btw there's a `DEF $Duration$` in the library `General/utils.ccu` for that assuming I did things correctly)

**Comment by Icohedron** [comment]
What does GLOBAL do?
I'm assuming it allows things to be seen when another ccu file imports it.
But those DEFs in the libraries don't have GLOBAL.

**Comment by Aquafina-water-bottle** [comment]
It's for visibility purposes. When a DEF / ARRAY / FUNC is placed anywhere after one tab space, only that tab space region can actually see the variable unless 'GLOBAL' is attached to it (where the entire document can see it including imported documents)
