### ISSUE TITLE
'minecraft:' prefix applied in bad context

### ISSUE THREAD

**Issue by Icohedron** [Aquafina-water-bottle/Command-Compiler-Unlimited#4]
Input:
```
pictionary clear
```
Output:
```
pictionary minecraft:clear
```

**Comment by Icohedron** [comment]
Don't go adding a special case for 'pictionary' in there! Maybe you should the the context of a keyword before it gets replaced as a command.
Hint: RegEx could help

**Comment by Aquafina-water-bottle** [comment]
Try adding 'pictionary' to the array in the config file named "minecraftCommandsArray". This shouldn't happen after that.
